// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package casbin_rule

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	casbinRuleFieldNames        []string
	casbinRuleRows              string
	casbinRuleRowsExpectAutoSet string

	cacheJzeroadminCasbinRuleIdPrefix = "cache:jzeroadmin:casbinRule:id:"
)

const (
	Id    condition.Field = "id"
	PType condition.Field = "p_type"
	V0    condition.Field = "v0"
	V1    condition.Field = "v1"
	V2    condition.Field = "v2"
	V3    condition.Field = "v3"
	V4    condition.Field = "v4"
	V5    condition.Field = "v5"
)

func initVars() {
	casbinRuleFieldNames = condition.RawFieldNames(&CasbinRule{})
	casbinRuleRows = strings.Join(casbinRuleFieldNames, ",")
	casbinRuleRowsExpectAutoSet = strings.Join(condition.RemoveIgnoreColumns(casbinRuleFieldNames, "`id`"), ",")
}

type (
	casbinRuleModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *CasbinRule) (sql.Result, error)
		InsertWithCache(ctx context.Context, session sqlx.Session, data *CasbinRule) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*CasbinRule, error)
		FindOneWithCache(ctx context.Context, session sqlx.Session, id int64) (*CasbinRule, error)
		Update(ctx context.Context, session sqlx.Session, data *CasbinRule) error
		UpdateWithCache(ctx context.Context, session sqlx.Session, data *CasbinRule) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
		DeleteWithCache(ctx context.Context, session sqlx.Session, id int64) error

		// custom interface generated by jzero
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*CasbinRule) error
		FindByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*CasbinRule, error)
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conds ...condition.Condition) ([]*CasbinRule, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (*CasbinRule, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*CasbinRule, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conds ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) error
	}

	defaultCasbinRuleModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		table      string
	}

	CasbinRule struct {
		Id    int64          `db:"id"`
		PType sql.NullString `db:"p_type"`
		V0    sql.NullString `db:"v0"`
		V1    sql.NullString `db:"v1"`
		V2    sql.NullString `db:"v2"`
		V3    sql.NullString `db:"v3"`
		V4    sql.NullString `db:"v4"`
		V5    sql.NullString `db:"v5"`
	}
)

func newCasbinRuleModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultCasbinRuleModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initVars()

	return &defaultCasbinRuleModel{
		cachedConn: cachedConn,
		conn:       conn,
		table:      condition.AdaptTable("`casbin_rule`"),
	}
}
func (m *defaultCasbinRuleModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.AdaptField("`id`"), id))
	statement, args := sb.Build()
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultCasbinRuleModel) DeleteWithCache(ctx context.Context, session sqlx.Session, id int64) error {
	jzeroadminCasbinRuleIdKey := fmt.Sprintf("%s%v", cacheJzeroadminCasbinRuleIdPrefix, id)
	_, err := m.cachedConn.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		sb := sqlbuilder.DeleteFrom(m.table)
		sb.Where(sb.EQ(condition.AdaptField("`id`"), id))
		statement, args := sb.Build()
		if session != nil {
			return session.ExecCtx(ctx, statement, args...)
		}
		return conn.ExecCtx(ctx, statement, args...)
	}, jzeroadminCasbinRuleIdKey)
	return err
}

func (m *defaultCasbinRuleModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*CasbinRule, error) {
	sb := sqlbuilder.Select(casbinRuleRows).From(m.table)
	sb.Where(sb.EQ(condition.AdaptField("`id`"), id))
	sb.Limit(1)
	sql, args := sb.Build()
	var resp CasbinRule
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCasbinRuleModel) FindOneWithCache(ctx context.Context, session sqlx.Session, id int64) (*CasbinRule, error) {
	jzeroadminCasbinRuleIdKey := fmt.Sprintf("%s%v", cacheJzeroadminCasbinRuleIdPrefix, id)
	var resp CasbinRule
	err := m.cachedConn.QueryRowCtx(ctx, &resp, jzeroadminCasbinRuleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		sb := sqlbuilder.Select(casbinRuleRows).From(m.table)
		sb.Where(sb.EQ(condition.AdaptField("`id`"), id))
		sql, args := sb.Build()
		if session != nil {
			return session.QueryRowCtx(ctx, v, sql, args...)
		}
		return conn.QueryRowCtx(ctx, v, sql, args...)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCasbinRuleModel) Insert(ctx context.Context, session sqlx.Session, data *CasbinRule) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(casbinRuleRowsExpectAutoSet).
		Values(data.PType, data.V0, data.V1, data.V2, data.V3, data.V4, data.V5).Build()
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultCasbinRuleModel) InsertWithCache(ctx context.Context, session sqlx.Session, data *CasbinRule) (sql.Result, error) {
	jzeroadminCasbinRuleIdKey := fmt.Sprintf("%s%v", cacheJzeroadminCasbinRuleIdPrefix, data.Id)
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(casbinRuleRowsExpectAutoSet).
		Values(data.PType, data.V0, data.V1, data.V2, data.V3, data.V4, data.V5).Build()
	return m.cachedConn.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, statement, args...)
		}
		return conn.ExecCtx(ctx, statement, args...)
	}, jzeroadminCasbinRuleIdKey)
}
func (m *defaultCasbinRuleModel) Update(ctx context.Context, session sqlx.Session, data *CasbinRule) error {
	sb := sqlbuilder.Update(m.table)
	split := strings.Split(casbinRuleRowsExpectAutoSet, ",")
	var assigns []string
	for _, s := range split {
		assigns = append(assigns, sb.Assign(s, nil))
	}
	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.AdaptField("`id`"), nil))
	statement, _ := sb.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, data.PType, data.V0, data.V1, data.V2, data.V3, data.V4, data.V5, data.Id)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, data.PType, data.V0, data.V1, data.V2, data.V3, data.V4, data.V5, data.Id)
	}
	return err
}

func (m *defaultCasbinRuleModel) UpdateWithCache(ctx context.Context, session sqlx.Session, data *CasbinRule) error {
	jzeroadminCasbinRuleIdKey := fmt.Sprintf("%s%v", cacheJzeroadminCasbinRuleIdPrefix, data.Id)
	_, err := m.cachedConn.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		sb := sqlbuilder.Update(m.table)
		split := strings.Split(casbinRuleRowsExpectAutoSet, ",")
		var assigns []string
		for _, s := range split {
			assigns = append(assigns, sb.Assign(s, nil))
		}
		sb.Set(assigns...)
		sb.Where(sb.EQ(condition.AdaptField("`id`"), nil))
		statement, _ := sb.Build()
		if session != nil {
			return session.ExecCtx(ctx, statement, data.PType, data.V0, data.V1, data.V2, data.V3, data.V4, data.V5, data.Id)
		}
		return conn.ExecCtx(ctx, statement, data.PType, data.V0, data.V1, data.V2, data.V3, data.V4, data.V5, data.Id)
	}, jzeroadminCasbinRuleIdKey)
	return err
}

func (m *defaultCasbinRuleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheJzeroadminCasbinRuleIdPrefix, primary)
}

func (m *defaultCasbinRuleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	sb := sqlbuilder.Select(casbinRuleRows).From(m.table)
	sb.Where(sb.EQ(condition.AdaptField("`id`"), primary))
	sql, args := sb.Build()
	return conn.QueryRowCtx(ctx, v, sql, args...)
}

func (m *defaultCasbinRuleModel) TableName() string {
	return m.table
}

func (m *customCasbinRuleModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*CasbinRule) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(casbinRuleRowsExpectAutoSet)
	for _, data := range datas {
		sb.Values(data.PType, data.V0, data.V1, data.V2, data.V3, data.V4, data.V5)
	}
	statement, args := sb.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customCasbinRuleModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conds ...condition.Condition) ([]*CasbinRule, error) {
	sb := sqlbuilder.Select(columns...).From(m.table)
	builder := condition.Select(*sb, conds...)
	statement, args := builder.Build()

	var resp []*CasbinRule
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customCasbinRuleModel) FindByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*CasbinRule, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, casbinRuleFieldNames, conds...)
}

func (m *customCasbinRuleModel) CountByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (int64, error) {
	countsb := sqlbuilder.Select("count(*)").From(m.table)

	var countConds []condition.Condition
	for _, cond := range conds {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset {
			countConds = append(countConds, cond)
		}
	}
	countBuilder := condition.Select(*countsb, countConds...)

	var (
		total int64
		err   error
	)
	statement, args := countBuilder.Build()
	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customCasbinRuleModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (*CasbinRule, error) {
	sb := sqlbuilder.Select(casbinRuleFieldNames...).From(m.table)

	builder := condition.Select(*sb, conds...)
	builder.Limit(1)
	statement, args := builder.Build()

	var resp CasbinRule
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customCasbinRuleModel) PageByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*CasbinRule, int64, error) {
	sb := sqlbuilder.Select(casbinRuleFieldNames...).From(m.table)
	builder := condition.Select(*sb, conds...)

	var resp []*CasbinRule
	var err error

	statement, args := builder.Build()

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conds...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customCasbinRuleModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conds ...condition.Condition) error {
	if field == nil {
		return nil
	}

	sb := sqlbuilder.Update(m.table)
	builder := condition.Update(*sb, conds...)

	var assigns []string
	for key, value := range field {
		assigns = append(assigns, sb.Assign(key, value))
	}
	builder.Set(assigns...)

	statement, args := builder.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customCasbinRuleModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) error {
	if len(conds) == 0 {
		return nil
	}
	sb := sqlbuilder.DeleteFrom(m.table)
	builder := condition.Delete(*sb, conds...)
	statement, args := builder.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
