// Code generated by jzero. DO NOT EDIT.
package managerole

import (
	"time"
)

var (
	_ = time.Now()
)

type AddRequest struct {
	RoleName string `json:"roleName"`
	RoleCode string `json:"roleCode"`
	RoleDesc string `json:"roleDesc"`
	Status   string `json:"status"`
}

type AddResponse struct {
}

type DeleteRequest struct {
	Ids []uint64 `json:"ids"`
}

type DeleteResponse struct {
}

type EditRequest struct {
	Id       uint64 `json:"id"`
	RoleName string `json:"roleName"`
	RoleCode string `json:"roleCode"`
	RoleDesc string `json:"roleDesc"`
	Status   string `json:"status"`
}

type EditResponse struct {
}

type Empty struct {
}

type GetAllRequest struct {
}

type GetAllResponse struct {
	Id       uint64 `json:"id"`
	RoleName string `json:"roleName"`
	RoleCode string `json:"roleCode"`
}

type GetMenusRequest struct {
	RoleId uint64 `form:"roleId"`
}

type GetMenusResponse struct {
	MenuIds []uint64 `json:"menuIds"`
}

type ListRequest struct {
	PageRequest
	RoleName string `form:"roleName,optional"`
	RoleCode string `form:"roleCode,optional"`
	Status   string `form:"status,optional"`
}

type ListResponse struct {
	PageResponse
	Records []ManageRole `json:"records"`
}

type ManageRole struct {
	Id         uint64 `json:"id"`
	RoleName   string `json:"roleName"`
	RoleCode   string `json:"roleCode"`
	RoleDesc   string `json:"roleDesc"`
	Status     string `json:"status"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type PageRequest struct {
	Current int `form:"current,default=1,optional"`
	Size    int `form:"size,default=10,optional"`
}

type PageResponse struct {
	Current int   `json:"current"`
	Size    int   `json:"size"`
	Total   int64 `json:"total"`
}

type SetMenusRequest struct {
	RoleId  uint64   `json:"roleId"`
	MenuIds []uint64 `json:"menuIds"`
}

type SetMenusResponse struct {
}

type UpdateHomeRequest struct {
	RoleId uint64 `json:"roleId"`
	Home   string `json:"home"`
}
