// Code generated by jzero. DO NOT EDIT.
package managerole

import (
	"time"
)

var (
	_ = time.Now()
)

type AddRequest struct {
	RoleName string `json:"roleName"`
	RoleCode string `json:"roleCode"`
	RoleDesc string `json:"roleDesc"`
	Status   string `json:"status"`
}

type AddResponse struct {
}

type DeleteRequest struct {
	Uuids []string `json:"uuids"`
}

type DeleteResponse struct {
}

type EditRequest struct {
	Uuid     string `json:"uuid"`
	RoleName string `json:"roleName"`
	RoleCode string `json:"roleCode"`
	RoleDesc string `json:"roleDesc"`
	Status   string `json:"status"`
}

type EditResponse struct {
}

type GetAllRequest struct {
}

type GetAllResponse struct {
	Uuid     string `json:"uuid"`
	RoleName string `json:"roleName"`
	RoleCode string `json:"roleCode"`
}

type GetHomeRequest struct {
	RoleUuid string `form:"roleUuid"`
}

type GetMenusRequest struct {
	RoleUuid string `form:"roleUuid"`
}

type GetMenusResponse struct {
	MenuUuids []string `json:"menuUuids"`
}

type ListRequest struct {
	PageRequest
	RoleName string `form:"roleName,optional"`
	RoleCode string `form:"roleCode,optional"`
	Status   string `form:"status,optional"`
}

type ListResponse struct {
	PageResponse
	Records []ManageRole `json:"records"`
}

type ManageRole struct {
	Uuid       string `json:"uuid"`
	RoleName   string `json:"roleName"`
	RoleCode   string `json:"roleCode"`
	RoleDesc   string `json:"roleDesc"`
	Status     string `json:"status"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type PageRequest struct {
	Current int `form:"current,default=1,optional"`
	Size    int `form:"size,default=10,optional"`
}

type PageResponse struct {
	Current int   `json:"current"`
	Size    int   `json:"size"`
	Total   int64 `json:"total"`
}

type SetMenusRequest struct {
	RoleUuid  string   `json:"roleUuid"`
	MenuUuids []string `json:"menuUuids"`
}

type SetMenusResponse struct {
}

type UpdateHomeRequest struct {
	RoleUuid string `json:"roleUuid"`
	Home     string `json:"home"`
}

type UpdateHomeResponse struct {
}
