CREATE TABLE `manage_menu` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` bigint DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `status` varchar(1) NOT NULL,
  `parent_id` bigint NOT NULL,
  `menu_type` varchar(1) NOT NULL,
  `menu_name` varchar(50) NOT NULL,
  `hide_in_menu` tinyint(1) NOT NULL,
  `active_menu` varchar(50) DEFAULT NULL,
  `order` bigint NOT NULL,
  `route_name` varchar(255) NOT NULL,
  `route_path` varchar(255) NOT NULL,
  `component` varchar(255) NOT NULL,
  `icon` varchar(255) NOT NULL,
  `icon_type` varchar(1) NOT NULL,
  `i18n_key` varchar(255) NOT NULL,
  `keep_alive` tinyint(1) NOT NULL,
  `href` longtext,
  `multi_tab` tinyint(1) DEFAULT NULL,
  `fixed_index_in_tab` bigint NOT NULL,
  `query` longtext,
  `permissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `constant` tinyint(1) NOT NULL,
  `button_code` longtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci