CREATE TABLE `system_menu` (
    `id` integer AUTO_INCREMENT,
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `create_by` integer DEFAULT NULL,
    `update_by` integer DEFAULT NULL,
    `status` varchar(1) NOT NULL DEFAULT '0',
    `parent_id` integer NOT NULL DEFAULT 0,
    `menu_type` varchar(1) NOT NULL DEFAULT '0',
    `menu_name` varchar(50) NOT NULL DEFAULT '',
    `hide_in_menu` tinyint(1) NOT NULL DEFAULT 0,
    `active_menu` varchar(50) DEFAULT NULL,
    `order` integer NOT NULL DEFAULT 0,
    `route_name` varchar(255) NOT NULL DEFAULT '',
    `route_path` varchar(255) NOT NULL DEFAULT '',
    `component` varchar(255) NOT NULL DEFAULT '',
    `icon` varchar(255) NOT NULL DEFAULT '',
    `icon_type` varchar(1) NOT NULL DEFAULT '',
    `i18n_key` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
)ENGINE = InnoDB COLLATE utf8mb4_general_ci;