// Code generated by jzero. DO NOT EDIT.
package systemmenu

import (
	"time"
)

var (
	_ = time.Now()
)

type GetAllPagesRequest struct {
}

type ListRequest struct {
}

type ListResponse struct {
}

type TreeRequest struct {
}

type TreeResponse struct {
	Id       uint64         `json:"id"`
	Label    string         `json:"label"`
	PId      uint64         `json:"pId"`
	Children []TreeResponse `json:"children"`
}
