// Code generated by jzero. DO NOT EDIT.
package v1auth

import (
	"time"
)

var (
	_ = time.Now()
)

type CodeLoginRequest struct {
	Email            string `json:"email"`
	VerificationUuid string `json:"verificationUuid"`
	VerificationCode string `json:"verificationCode"`
}

type GetUserInfoRequest struct {
}

type GetUserInfoResponse struct {
	UserUuid string   `json:"userUuid"`
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
	Buttons  []string `json:"buttons"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type PwdLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type RegisterRequest struct {
	Email            string `json:"email"`
	VerificationUuid string `json:"verificationUuid"`
	VerificationCode string `json:"verificationCode"`
	Username         string `json:"username"`
	Password         string `json:"password"`
}

type RegisterResponse struct {
}

type ResetPasswordRequest struct {
	Email            string `json:"email"`
	VerificationUuid string `json:"verificationUuid"`
	VerificationCode string `json:"verificationCode"`
	Password         string `json:"password"`
}

type ResetPasswordResponse struct {
}

type SendVerificationCodeRequest struct {
	Email            string `form:"email" validate:"email"`
	VerificationType string `form:"verificationType,option=email|phone"`
}

type SendVerificationCodeResponse struct {
	VerificationUuid string `json:"verificationUuid"`
}
