// Code generated by goctl. DO NOT EDIT.

package system_user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero-contrib/condition"
	"github.com/jzero-io/jzero-contrib/modelx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	systemUserFieldNames          = builder.RawFieldNames(&SystemUser{})
	systemUserRows                = strings.Join(systemUserFieldNames, ",")
	systemUserRowsExpectAutoSet   = strings.Join(stringx.Remove(systemUserFieldNames, "`id`"), ",")
	systemUserRowsWithPlaceHolder = strings.Join(stringx.Remove(systemUserFieldNames, "`id`"), "=?,") + "=?"

	cacheSystemUserIdPrefix       = "jzero-admin:cache:systemUser:id:"
	cacheSystemUserUsernamePrefix = "jzero-admin:cache:systemUser:username:"
)

type (
	systemUserModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SystemUser) (sql.Result, error)
		InsertWithCache(ctx context.Context, session sqlx.Session, data *SystemUser) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id uint64) (*SystemUser, error)
		FindOneWithCache(ctx context.Context, session sqlx.Session, id uint64) (*SystemUser, error)
		FindOneByUsername(ctx context.Context, session sqlx.Session, username string) (*SystemUser, error)
		FindOneByUsernameWithCache(ctx context.Context, session sqlx.Session, username string) (*SystemUser, error)
		Update(ctx context.Context, session sqlx.Session, data *SystemUser) error
		UpdateWithCache(ctx context.Context, session sqlx.Session, data *SystemUser) error
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
		DeleteWithCache(ctx context.Context, session sqlx.Session, id uint64) error

		// custom interface generated by jzero
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*SystemUser) error
		FindByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*SystemUser, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (*SystemUser, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*SystemUser, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conds ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) error
	}

	defaultSystemUserModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		table      string
	}

	SystemUser struct {
		Id         uint64         `db:"id"`
		CreateTime time.Time      `db:"create_time"`
		UpdateTime time.Time      `db:"update_time"`
		CreateBy   sql.NullInt64  `db:"create_by"`
		UpdateBy   sql.NullInt64  `db:"update_by"`
		Username   string         `db:"username"`
		Password   string         `db:"password"`
		Nickname   string         `db:"nickname"`
		Gender     string         `db:"gender"`
		Phone      sql.NullString `db:"phone"`
		Status     string         `db:"status"`
		Email      sql.NullString `db:"email"`
	}
)

func newSystemUserModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultSystemUserModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}
	return &defaultSystemUserModel{
		cachedConn: cachedConn,
		conn:       conn,
		table:      "`system_user`",
	}
}
func (m *defaultSystemUserModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ("`id`", id))
	statement, args := sb.Build()
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultSystemUserModel) DeleteWithCache(ctx context.Context, session sqlx.Session, id uint64) error {
	data, err := m.FindOne(ctx, session, id)
	if err != nil {
		return err
	}

	systemUserIdKey := fmt.Sprintf("%s%v", cacheSystemUserIdPrefix, id)
	systemUserUsernameKey := fmt.Sprintf("%s%v", cacheSystemUserUsernamePrefix, data.Username)
	_, err = m.cachedConn.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		sb := sqlbuilder.DeleteFrom(m.table)
		sb.Where(sb.EQ("`id`", id))
		statement, args := sb.Build()
		if session != nil {
			return session.ExecCtx(ctx, statement, args...)
		}
		return conn.ExecCtx(ctx, statement, args...)
	}, systemUserIdKey, systemUserUsernameKey)
	return err
}

func (m *defaultSystemUserModel) FindOne(ctx context.Context, session sqlx.Session, id uint64) (*SystemUser, error) {
	sb := sqlbuilder.Select(systemUserRows).From(m.table)
	sb.Where(sb.EQ("`id`", id))
	sb.Limit(1)
	sql, args := sb.Build()
	var resp SystemUser
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemUserModel) FindOneWithCache(ctx context.Context, session sqlx.Session, id uint64) (*SystemUser, error) {
	systemUserIdKey := fmt.Sprintf("%s%v", cacheSystemUserIdPrefix, id)
	var resp SystemUser
	err := m.cachedConn.QueryRowCtx(ctx, &resp, systemUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		sb := sqlbuilder.Select(systemUserRows).From(m.table)
		sb.Where(sb.EQ("`id`", id))
		sql, args := sb.Build()
		if session != nil {
			return session.QueryRowCtx(ctx, v, sql, args...)
		}
		return conn.QueryRowCtx(ctx, v, sql, args...)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemUserModel) FindOneByUsername(ctx context.Context, session sqlx.Session, username string) (*SystemUser, error) {
	var resp SystemUser
	var err error

	sb := sqlbuilder.Select(systemUserRows).From(m.table)
	sb.Where(sb.EQ(strings.Split(strings.ReplaceAll("`username` = ?", " ", ""), "=")[0], username))
	sb.Limit(1)

	sql, args := sb.Build()

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemUserModel) FindOneByUsernameWithCache(ctx context.Context, session sqlx.Session, username string) (*SystemUser, error) {
	systemUserUsernameKey := fmt.Sprintf("%s%v", cacheSystemUserUsernamePrefix, username)
	var resp SystemUser
	err := m.cachedConn.QueryRowIndexCtx(ctx, &resp, systemUserUsernameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		sb := sqlbuilder.Select(systemUserRows).From(m.table)
		sb.Where(sb.EQ(strings.Split(strings.ReplaceAll("`username` = ?", " ", ""), "=")[0], username))
		sb.Limit(1)
		sql, args := sb.Build()
		var err error

		if session != nil {
			err = session.QueryRowCtx(ctx, &resp, sql, args...)
		} else {
			err = conn.QueryRowCtx(ctx, &resp, sql, args...)
		}
		if err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemUserModel) Insert(ctx context.Context, session sqlx.Session, data *SystemUser) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(systemUserRowsExpectAutoSet).
		Values(data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.Username, data.Password, data.Nickname, data.Gender, data.Phone, data.Status, data.Email).Build()
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultSystemUserModel) InsertWithCache(ctx context.Context, session sqlx.Session, data *SystemUser) (sql.Result, error) {
	systemUserIdKey := fmt.Sprintf("%s%v", cacheSystemUserIdPrefix, data.Id)
	systemUserUsernameKey := fmt.Sprintf("%s%v", cacheSystemUserUsernamePrefix, data.Username)
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(systemUserRowsExpectAutoSet).
		Values(data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.Username, data.Password, data.Nickname, data.Gender, data.Phone, data.Status, data.Email).Build()
	return m.cachedConn.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		if session != nil {
			return session.ExecCtx(ctx, statement, args...)
		}
		return conn.ExecCtx(ctx, statement, args...)
	}, systemUserIdKey, systemUserUsernameKey)
}
func (m *defaultSystemUserModel) Update(ctx context.Context, session sqlx.Session, newData *SystemUser) error {
	sb := sqlbuilder.Update(m.table)
	split := strings.Split(systemUserRowsExpectAutoSet, ",")
	var assigns []string
	for _, s := range split {
		assigns = append(assigns, sb.Assign(s, nil))
	}
	sb.Set(assigns...)
	sb.Where(sb.EQ("`id`", nil))
	statement, _ := sb.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, newData.CreateTime, newData.UpdateTime, newData.CreateBy, newData.UpdateBy, newData.Username, newData.Password, newData.Nickname, newData.Gender, newData.Phone, newData.Status, newData.Email, newData.Id)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, newData.CreateTime, newData.UpdateTime, newData.CreateBy, newData.UpdateBy, newData.Username, newData.Password, newData.Nickname, newData.Gender, newData.Phone, newData.Status, newData.Email, newData.Id)
	}
	return err
}

func (m *defaultSystemUserModel) UpdateWithCache(ctx context.Context, session sqlx.Session, newData *SystemUser) error {
	data, err := m.FindOne(ctx, session, newData.Id)
	if err != nil {
		return err
	}
	systemUserIdKey := fmt.Sprintf("%s%v", cacheSystemUserIdPrefix, data.Id)
	systemUserUsernameKey := fmt.Sprintf("%s%v", cacheSystemUserUsernamePrefix, data.Username)
	_, err = m.cachedConn.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		sb := sqlbuilder.Update(m.table)
		split := strings.Split(systemUserRowsExpectAutoSet, ",")
		var assigns []string
		for _, s := range split {
			assigns = append(assigns, sb.Assign(s, nil))
		}
		sb.Set(assigns...)
		sb.Where(sb.EQ("`id`", nil))
		statement, _ := sb.Build()
		if session != nil {
			return session.ExecCtx(ctx, statement, newData.CreateTime, newData.UpdateTime, newData.CreateBy, newData.UpdateBy, newData.Username, newData.Password, newData.Nickname, newData.Gender, newData.Phone, newData.Status, newData.Email, newData.Id)
		}
		return conn.ExecCtx(ctx, statement, newData.CreateTime, newData.UpdateTime, newData.CreateBy, newData.UpdateBy, newData.Username, newData.Password, newData.Nickname, newData.Gender, newData.Phone, newData.Status, newData.Email, newData.Id)
	}, systemUserIdKey, systemUserUsernameKey)
	return err
}

func (m *defaultSystemUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSystemUserIdPrefix, primary)
}

func (m *defaultSystemUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	sb := sqlbuilder.Select(systemUserRows).From(m.table)
	sb.Where(sb.EQ("`id`", primary))
	sql, args := sb.Build()
	return conn.QueryRowCtx(ctx, v, sql, args...)
}

func (m *defaultSystemUserModel) tableName() string {
	return m.table
}

func (m *customSystemUserModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*SystemUser) error {
	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(systemUserRowsExpectAutoSet)
	for _, data := range datas {
		sb.Values(data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.Username, data.Password, data.Nickname, data.Gender, data.Phone, data.Status, data.Email)
	}
	statement, args := sb.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customSystemUserModel) FindByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*SystemUser, error) {
	sb := sqlbuilder.Select(systemUserFieldNames...).From(m.table)
	condition.ApplySelect(sb, conds...)
	statement, args := sb.Build()

	var resp []*SystemUser
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customSystemUserModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (*SystemUser, error) {
	sb := sqlbuilder.Select(systemUserFieldNames...).From(m.table)

	condition.ApplySelect(sb, conds...)
	sb.Limit(1)
	statement, args := sb.Build()

	var resp SystemUser
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customSystemUserModel) PageByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*SystemUser, int64, error) {
	sb := sqlbuilder.Select(systemUserFieldNames...).From(m.table)
	countsb := sqlbuilder.Select("count(*)").From(m.table)

	condition.ApplySelect(sb, conds...)

	var countConds []condition.Condition
	for _, cond := range conds {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset {
			countConds = append(countConds, cond)
		}
	}
	condition.ApplySelect(countsb, countConds...)

	var resp []*SystemUser
	var err error

	statement, args := sb.Build()

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	var total int64
	statement, args = countsb.Build()
	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customSystemUserModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conds ...condition.Condition) error {
	if field == nil {
		return nil
	}

	sb := sqlbuilder.Update(m.table)
	condition.ApplyUpdate(sb, conds...)

	var assigns []string
	for key, value := range field {
		assigns = append(assigns, sb.Assign(key, value))
	}
	sb.Set(assigns...)

	statement, args := sb.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customSystemUserModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) error {
	if len(conds) == 0 {
		return nil
	}
	sb := sqlbuilder.DeleteFrom(m.table)
	condition.ApplyDelete(sb, conds...)
	statement, args := sb.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
