// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package manage_menu_role_permission

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero-contrib/condition"
	"github.com/jzero-io/jzero-contrib/modelx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	manageMenuRolePermissionFieldNames          = builder.RawFieldNames(&ManageMenuRolePermission{})
	manageMenuRolePermissionRows                = strings.Join(manageMenuRolePermissionFieldNames, ",")
	manageMenuRolePermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(manageMenuRolePermissionFieldNames, "`id`"), ",")
	manageMenuRolePermissionRowsWithPlaceHolder = strings.Join(stringx.Remove(manageMenuRolePermissionFieldNames, "`id`"), "=?,") + "=?"
)

type (
	manageMenuRolePermissionModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ManageMenuRolePermission) (sql.Result, error)
		InsertWithCache(ctx context.Context, session sqlx.Session, data *ManageMenuRolePermission) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id uint64) (*ManageMenuRolePermission, error)
		FindOneWithCache(ctx context.Context, session sqlx.Session, id uint64) (*ManageMenuRolePermission, error)
		Update(ctx context.Context, session sqlx.Session, data *ManageMenuRolePermission) error
		UpdateWithCache(ctx context.Context, session sqlx.Session, data *ManageMenuRolePermission) error
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
		DeleteWithCache(ctx context.Context, session sqlx.Session, id uint64) error

		// custom interface generated by jzero
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*ManageMenuRolePermission) error
		FindByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*ManageMenuRolePermission, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (*ManageMenuRolePermission, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*ManageMenuRolePermission, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conds ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) error
	}

	defaultManageMenuRolePermissionModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		table      string
	}

	ManageMenuRolePermission struct {
		Id           uint64        `db:"id"`
		CreateTime   time.Time     `db:"create_time"`
		UpdateTime   time.Time     `db:"update_time"`
		CreateBy     sql.NullInt64 `db:"create_by"`
		UpdateBy     sql.NullInt64 `db:"update_by"`
		RoleId       int64         `db:"role_id"`
		PermissionId int64         `db:"permission_id"`
	}
)

func newManageMenuRolePermissionModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultManageMenuRolePermissionModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}
	return &defaultManageMenuRolePermissionModel{
		cachedConn: cachedConn,
		conn:       conn,
		table:      "`manage_menu_role_permission`",
	}
}
func (m *defaultManageMenuRolePermissionModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ("`id`", id))
	statement, args := sb.Build()
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultManageMenuRolePermissionModel) DeleteWithCache(ctx context.Context, session sqlx.Session, id uint64) error {
	return m.Delete(ctx, session, id)
}

func (m *defaultManageMenuRolePermissionModel) FindOne(ctx context.Context, session sqlx.Session, id uint64) (*ManageMenuRolePermission, error) {
	sb := sqlbuilder.Select(manageMenuRolePermissionRows).From(m.table)
	sb.Where(sb.EQ("`id`", id))
	sb.Limit(1)
	sql, args := sb.Build()
	var resp ManageMenuRolePermission
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManageMenuRolePermissionModel) FindOneWithCache(ctx context.Context, session sqlx.Session, id uint64) (*ManageMenuRolePermission, error) {
	return m.FindOne(ctx, session, id)
}

func (m *defaultManageMenuRolePermissionModel) Insert(ctx context.Context, session sqlx.Session, data *ManageMenuRolePermission) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(manageMenuRolePermissionRowsExpectAutoSet).
		Values(data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.RoleId, data.PermissionId).Build()
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultManageMenuRolePermissionModel) InsertWithCache(ctx context.Context, session sqlx.Session, data *ManageMenuRolePermission) (sql.Result, error) {
	return m.Insert(ctx, session, data)
}
func (m *defaultManageMenuRolePermissionModel) Update(ctx context.Context, session sqlx.Session, data *ManageMenuRolePermission) error {
	sb := sqlbuilder.Update(m.table)
	split := strings.Split(manageMenuRolePermissionRowsExpectAutoSet, ",")
	var assigns []string
	for _, s := range split {
		assigns = append(assigns, sb.Assign(s, nil))
	}
	sb.Set(assigns...)
	sb.Where(sb.EQ("`id`", nil))
	statement, _ := sb.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.RoleId, data.PermissionId, data.Id)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.RoleId, data.PermissionId, data.Id)
	}
	return err
}

func (m *defaultManageMenuRolePermissionModel) UpdateWithCache(ctx context.Context, session sqlx.Session, data *ManageMenuRolePermission) error {
	return m.Update(ctx, session, data)
}

func (m *defaultManageMenuRolePermissionModel) tableName() string {
	return m.table
}

func (m *customManageMenuRolePermissionModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*ManageMenuRolePermission) error {
	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(manageMenuRolePermissionRowsExpectAutoSet)
	for _, data := range datas {
		sb.Values(data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.RoleId, data.PermissionId)
	}
	statement, args := sb.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customManageMenuRolePermissionModel) FindByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*ManageMenuRolePermission, error) {
	sb := sqlbuilder.Select(manageMenuRolePermissionFieldNames...).From(m.table)
	builder := condition.Select(*sb, conds...)
	statement, args := builder.Build()

	var resp []*ManageMenuRolePermission
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customManageMenuRolePermissionModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (*ManageMenuRolePermission, error) {
	sb := sqlbuilder.Select(manageMenuRolePermissionFieldNames...).From(m.table)

	builder := condition.Select(*sb, conds...)
	builder.Limit(1)
	statement, args := builder.Build()

	var resp ManageMenuRolePermission
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customManageMenuRolePermissionModel) PageByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*ManageMenuRolePermission, int64, error) {
	sb := sqlbuilder.Select(manageMenuRolePermissionFieldNames...).From(m.table)
	countsb := sqlbuilder.Select("count(*)").From(m.table)

	builder := condition.Select(*sb, conds...)

	var countConds []condition.Condition
	for _, cond := range conds {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset {
			countConds = append(countConds, cond)
		}
	}
	countBuilder := condition.Select(*countsb, countConds...)

	var resp []*ManageMenuRolePermission
	var err error

	statement, args := builder.Build()

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	var total int64
	statement, args = countBuilder.Build()
	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customManageMenuRolePermissionModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conds ...condition.Condition) error {
	if field == nil {
		return nil
	}

	sb := sqlbuilder.Update(m.table)
	builder := condition.Update(*sb, conds...)

	var assigns []string
	for key, value := range field {
		assigns = append(assigns, sb.Assign(key, value))
	}
	builder.Set(assigns...)

	statement, args := builder.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customManageMenuRolePermissionModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) error {
	if len(conds) == 0 {
		return nil
	}
	sb := sqlbuilder.DeleteFrom(m.table)
	builder := condition.Delete(*sb, conds...)
	statement, args := builder.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
