// Code generated by jzero. DO NOT EDIT.
package systemrole

import (
	"time"
)

var (
	_ = time.Now()
)

type GetAllRequest struct {
}

type GetAllResponse struct {
}

type ListRequest struct {
}

type ListResponse struct {
}
