// Code generated by jzero. DO NOT EDIT.
package auth

import (
	"time"
)

var (
	_ = time.Now()
)

type ErrorRequest struct {
}

type ErrorResponse struct {
}

type GetUserInfoRequest struct {
}

type GetUserInfoResponse struct {
	UserId   string   `json:"userId"`
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
	Buttons  []string `json:"buttons"`
}

type LoginRequest struct {
	Username string `json:"username,optional"`
	Password string `json:"password,opitional"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenRequest struct {
}

type RefreshTokenResponse struct {
}

type RegisterRequest struct {
	Email            string `json:"email"`
	VerificationUuid string `json:"verificationUuid"`
	VerificationCode string `json:"verificationCode"`
	Username         string `json:"username"`
	Password         string `json:"password"`
}

type RegisterResponse struct {
}

type SendVerificationCodeRequest struct {
	Email            string `form:"email" validate:"email"`
	VerificationType string `form:"verificationType,option=email|phone"`
}

type SendVerificationCodeResponse struct {
	VerificationUuid string `json:"verificationUuid"`
}
