// Code generated by jzero. DO NOT EDIT.
package auth

import (
	"time"
)

var (
	_ = time.Now()
)

type ErrorRequest struct {
}

type ErrorResponse struct {
}

type GetUserInfoRequest struct {
}

type GetUserInfoResponse struct {
}

type LoginRequest struct {
}

type LoginResponse struct {
}

type RefreshTokenRequest struct {
}

type RefreshTokenResponse struct {
}
