// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package system_menu

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero-contrib/condition"
	"github.com/jzero-io/jzero-contrib/modelx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	systemMenuFieldNames          = builder.RawFieldNames(&SystemMenu{})
	systemMenuRows                = strings.Join(systemMenuFieldNames, ",")
	systemMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(systemMenuFieldNames, "`id`"), ",")
	systemMenuRowsWithPlaceHolder = strings.Join(stringx.Remove(systemMenuFieldNames, "`id`"), "=?,") + "=?"
)

type (
	systemMenuModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SystemMenu) (sql.Result, error)
		InsertWithCache(ctx context.Context, session sqlx.Session, data *SystemMenu) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id uint64) (*SystemMenu, error)
		FindOneWithCache(ctx context.Context, session sqlx.Session, id uint64) (*SystemMenu, error)
		Update(ctx context.Context, session sqlx.Session, data *SystemMenu) error
		UpdateWithCache(ctx context.Context, session sqlx.Session, data *SystemMenu) error
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
		DeleteWithCache(ctx context.Context, session sqlx.Session, id uint64) error

		// custom interface generated by jzero
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*SystemMenu) error
		FindByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*SystemMenu, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (*SystemMenu, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*SystemMenu, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conds ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) error
	}

	defaultSystemMenuModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		table      string
	}

	SystemMenu struct {
		Id              uint64         `db:"id"`
		CreateTime      time.Time      `db:"create_time"`
		UpdateTime      time.Time      `db:"update_time"`
		CreateBy        sql.NullInt64  `db:"create_by"`
		UpdateBy        sql.NullInt64  `db:"update_by"`
		Status          string         `db:"status"`
		ParentId        int64          `db:"parent_id"`
		MenuType        string         `db:"menu_type"`
		MenuName        string         `db:"menu_name"`
		HideInMenu      int64          `db:"hide_in_menu"`
		ActiveMenu      sql.NullString `db:"active_menu"`
		Order           int64          `db:"order"`
		RouteName       string         `db:"route_name"`
		RoutePath       string         `db:"route_path"`
		Component       string         `db:"component"`
		Icon            string         `db:"icon"`
		IconType        string         `db:"icon_type"`
		I18nKey         string         `db:"i18n_key"`
		KeepAlive       int64          `db:"keep_alive"`
		Href            sql.NullString `db:"href"`
		MultiTab        sql.NullInt64  `db:"multi_tab"`
		FixedIndexInTab int64          `db:"fixed_index_in_tab"`
		Query           sql.NullString `db:"query"`
		Buttons         sql.NullString `db:"buttons"`
		Constant        int64          `db:"constant"`
	}
)

func newSystemMenuModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultSystemMenuModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}
	return &defaultSystemMenuModel{
		cachedConn: cachedConn,
		conn:       conn,
		table:      "`system_menu`",
	}
}
func (m *defaultSystemMenuModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ("`id`", id))
	statement, args := sb.Build()
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultSystemMenuModel) DeleteWithCache(ctx context.Context, session sqlx.Session, id uint64) error {
	return m.Delete(ctx, session, id)
}

func (m *defaultSystemMenuModel) FindOne(ctx context.Context, session sqlx.Session, id uint64) (*SystemMenu, error) {
	sb := sqlbuilder.Select(systemMenuRows).From(m.table)
	sb.Where(sb.EQ("`id`", id))
	sb.Limit(1)
	sql, args := sb.Build()
	var resp SystemMenu
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemMenuModel) FindOneWithCache(ctx context.Context, session sqlx.Session, id uint64) (*SystemMenu, error) {
	return m.FindOne(ctx, session, id)
}

func (m *defaultSystemMenuModel) Insert(ctx context.Context, session sqlx.Session, data *SystemMenu) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(systemMenuRowsExpectAutoSet).
		Values(data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.Status, data.ParentId, data.MenuType, data.MenuName, data.HideInMenu, data.ActiveMenu, data.Order, data.RouteName, data.RoutePath, data.Component, data.Icon, data.IconType, data.I18nKey, data.KeepAlive, data.Href, data.MultiTab, data.FixedIndexInTab, data.Query, data.Buttons, data.Constant).Build()
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultSystemMenuModel) InsertWithCache(ctx context.Context, session sqlx.Session, data *SystemMenu) (sql.Result, error) {
	return m.Insert(ctx, session, data)
}
func (m *defaultSystemMenuModel) Update(ctx context.Context, session sqlx.Session, data *SystemMenu) error {
	sb := sqlbuilder.Update(m.table)
	split := strings.Split(systemMenuRowsExpectAutoSet, ",")
	var assigns []string
	for _, s := range split {
		assigns = append(assigns, sb.Assign(s, nil))
	}
	sb.Set(assigns...)
	sb.Where(sb.EQ("`id`", nil))
	statement, _ := sb.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.Status, data.ParentId, data.MenuType, data.MenuName, data.HideInMenu, data.ActiveMenu, data.Order, data.RouteName, data.RoutePath, data.Component, data.Icon, data.IconType, data.I18nKey, data.KeepAlive, data.Href, data.MultiTab, data.FixedIndexInTab, data.Query, data.Buttons, data.Constant, data.Id)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.Status, data.ParentId, data.MenuType, data.MenuName, data.HideInMenu, data.ActiveMenu, data.Order, data.RouteName, data.RoutePath, data.Component, data.Icon, data.IconType, data.I18nKey, data.KeepAlive, data.Href, data.MultiTab, data.FixedIndexInTab, data.Query, data.Buttons, data.Constant, data.Id)
	}
	return err
}

func (m *defaultSystemMenuModel) UpdateWithCache(ctx context.Context, session sqlx.Session, data *SystemMenu) error {
	return m.Update(ctx, session, data)
}

func (m *defaultSystemMenuModel) tableName() string {
	return m.table
}

func (m *customSystemMenuModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*SystemMenu) error {
	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(systemMenuRowsExpectAutoSet)
	for _, data := range datas {
		sb.Values(data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.Status, data.ParentId, data.MenuType, data.MenuName, data.HideInMenu, data.ActiveMenu, data.Order, data.RouteName, data.RoutePath, data.Component, data.Icon, data.IconType, data.I18nKey, data.KeepAlive, data.Href, data.MultiTab, data.FixedIndexInTab, data.Query, data.Buttons, data.Constant)
	}
	statement, args := sb.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customSystemMenuModel) FindByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*SystemMenu, error) {
	sb := sqlbuilder.Select(systemMenuFieldNames...).From(m.table)
	builder := condition.Select(*sb, conds...)
	statement, args := builder.Build()

	var resp []*SystemMenu
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customSystemMenuModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (*SystemMenu, error) {
	sb := sqlbuilder.Select(systemMenuFieldNames...).From(m.table)

	builder := condition.Select(*sb, conds...)
	builder.Limit(1)
	statement, args := builder.Build()

	var resp SystemMenu
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customSystemMenuModel) PageByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*SystemMenu, int64, error) {
	sb := sqlbuilder.Select(systemMenuFieldNames...).From(m.table)
	countsb := sqlbuilder.Select("count(*)").From(m.table)

	builder := condition.Select(*sb, conds...)

	var countConds []condition.Condition
	for _, cond := range conds {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset {
			countConds = append(countConds, cond)
		}
	}
	countBuilder := condition.Select(*countsb, countConds...)

	var resp []*SystemMenu
	var err error

	statement, args := builder.Build()

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	var total int64
	statement, args = countBuilder.Build()
	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customSystemMenuModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conds ...condition.Condition) error {
	if field == nil {
		return nil
	}

	sb := sqlbuilder.Update(m.table)
	builder := condition.Update(*sb, conds...)

	var assigns []string
	for key, value := range field {
		assigns = append(assigns, sb.Assign(key, value))
	}
	builder.Set(assigns...)

	statement, args := builder.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customSystemMenuModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) error {
	if len(conds) == 0 {
		return nil
	}
	sb := sqlbuilder.DeleteFrom(m.table)
	builder := condition.Delete(*sb, conds...)
	statement, args := builder.Build()

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
