// Code generated by jzero. DO NOT EDIT.
package common

import (
	"time"
)

var (
	_ = time.Now()
)

type PageRequest struct {
	Current int `form:"current,default=1,optional"`
	Size    int `form:"size,default=10,optional"`
}
