hooks:
  before:
    - go install tool

gen:
  hooks:
    after:
      - jzero gen swagger

  style: go_zero
  git-change: true
  route2Code: true

  model-driver: mysql
  model-cache: false
  model-ignore-columns: []
  model-schema: jzeroadmin

  swagger:
    merge: true