syntax: v1

gen:
  hooks:
    after:
      - jzero gen swagger
  style: go_zero
  git-change: true
  split-api-types-dir: true
  change-logic-types: true
  regen-api-types: true
  regen-api-handler: true

  model-mysql-ignore-columns: []