new:
  home: .template/jzero-admin-plugin

gen:
  hooks:
    after:
      - jzero gen swagger

  style: go_zero
  git-change: true
  route2Code: true

  model-driver: mysql
  model-cache: false
  model-ignore-columns: []
  model-schema: jzero-admin