syntax: v1

gen:
  hooks:
    after:
      - jzero gen swagger
  style: go_zero
  git-change: true
  split-api-types-dir: true
  change-logic-types: true
  regen-api-types: true
  regen-api-handler: true
  route2Code: true

  model-git-change-path: tools/migrate/tables
  model-mysql-datasource: true
  model-mysql-datasource-url: "root:123456@tcp(localhost:3306)/jzeroadmin"
  model-mysql-cache: true
  model-mysql-ignore-columns: []
  gen-mysql-create-table-ddl: true
  model-mysql-ddl-database: jzeroadmin