// Code generated by jzero. DO NOT EDIT.
package plugins

import (
	"github.com/zeromicro/go-zero/rest"

	"github.com/jzero-io/jzero-admin/server/internal/svc"
)

func LoadPlugins(server *rest.Server, svcCtx *svc.ServiceContext) {

}
