// Code generated by jzero. DO NOT EDIT.
package route

import (
	"time"
)

var (
	_ = time.Now()
)

type GetConstantRoutesRequest struct {
}

type GetConstantRoutesResponse struct {
}

type GetUserRoutesRequest struct {
}

type GetUserRoutesResponse struct {
}

type IsRouteExistRequest struct {
}

type IsRouteExistResponse struct {
}
