// Code generated by jzero. DO NOT EDIT.
package route

import (
	"time"
)

var (
	_ = time.Now()
)

type GetConstantRoutesRequest struct {
}

type GetConstantRoutesResponseItem struct {
	Name      string    `json:"name"`
	Path      string    `json:"path"`
	Component string    `json:"component"`
	Props     bool      `json:"props"`
	Meta      RouteMeta `json:"meta"`
}

type GetUserRoutesRequest struct {
}

type GetUserRoutesResponse struct {
	Routes []Route `json:"routes"`
	Home   string  `json:"home"`
}

type IsRouteExistRequest struct {
}

type Query struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Route struct {
	Id        int64     `json:"-"`
	ParentId  int64     `json:"-"`
	Name      string    `json:"name"`
	Path      string    `json:"path"`
	Meta      RouteMeta `json:"meta"`
	Component string    `json:"component"`
	Props     bool      `json:"props"`
	Redirect  string    `json:"redirect"`
	Children  []Route   `json:"children"`
}

type RouteMeta struct {
	Title           string  `json:"title"`
	I18nKey         string  `json:"i18nKey"`
	Icon            string  `json:"icon"`
	Order           int     `json:"order"`
	HideInMenu      bool    `json:"hideInMenu"`
	ActiveMenu      string  `json:"activeMenu"`
	MultiTab        bool    `json:"multiTab"`
	FixedIndexInTab *int64  `json:"fixedIndexInTab"`
	KeepAlive       bool    `json:"keepAlive"`
	Constant        bool    `json:"constant"`
	Href            string  `json:"href"`
	Query           []Query `json:"query"`
}
