// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package swagger

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest/httpx"

	"github.com/jzero-io/jzero-admin/server/internal/logic/swagger"
	"github.com/jzero-io/jzero-admin/server/internal/svc"
)

func Swagger(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := swagger.NewSwagger(r.Context(), svcCtx, r, w)
		err := l.Swagger()
		if err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
		} else {
			httpx.Ok(w)
		}
	}
}
