// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package manage_email

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	manageEmailFieldNames        []string
	manageEmailRows              string
	manageEmailRowsExpectAutoSet string
)

const (
	Id         condition.Field = "id"
	Uuid       condition.Field = "uuid"
	CreateTime condition.Field = "create_time"
	UpdateTime condition.Field = "update_time"
	From       condition.Field = "from"
	Host       condition.Field = "host"
	Port       condition.Field = "port"
	Username   condition.Field = "username"
	Password   condition.Field = "password"
	EnableSsl  condition.Field = "enable_ssl"
	IsVerify   condition.Field = "is_verify"
)

func initManageEmailVars(flavor sqlbuilder.Flavor) {
	manageEmailFieldNames = condition.RawFieldNamesWithFlavor(flavor, &ManageEmail{})
	manageEmailRows = strings.Join(manageEmailFieldNames, ",")
	manageEmailRowsExpectAutoSet = strings.Join(condition.RemoveIgnoreColumnsWithFlavor(flavor, manageEmailFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
}

type (
	manageEmailModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *ManageEmail) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*ManageEmail, error)
		FindOneByUuid(ctx context.Context, session sqlx.Session, uuid string) (*ManageEmail, error)
		Update(ctx context.Context, session sqlx.Session, data *ManageEmail) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) manageEmailModel
		InsertV2(ctx context.Context, session sqlx.Session, data *ManageEmail) error
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*ManageEmail) error
		FindByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*ManageEmail, error)
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conds ...condition.Condition) ([]*ManageEmail, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (*ManageEmail, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*ManageEmail, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conds ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) error
	}

	defaultManageEmailModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	ManageEmail struct {
		Id         int64     `db:"id"`
		Uuid       string    `db:"uuid"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		From       string    `db:"from"`
		Host       string    `db:"host"`
		Port       int64     `db:"port"`
		Username   string    `db:"username"`
		Password   string    `db:"password"`
		EnableSsl  int64     `db:"enable_ssl"`
		IsVerify   int64     `db:"is_verify"`
	}
)

func newManageEmailModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultManageEmailModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initManageEmailVars(o.Flavor)

	return &defaultManageEmailModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "`manage_email`"),
	}
}

func (m *defaultManageEmailModel) clone() *defaultManageEmailModel {
	return &defaultManageEmailModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultManageEmailModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultManageEmailModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*ManageEmail, error) {
	sb := sqlbuilder.Select(manageEmailRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp ManageEmail
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManageEmailModel) FindOneByUuid(ctx context.Context, session sqlx.Session, uuid string) (*ManageEmail, error) {
	var resp ManageEmail
	var err error

	sb := sqlbuilder.Select(manageEmailRows).From(m.table)
	condition.SelectByWhereRawSql(sb, "`uuid` = ?", uuid)
	sb.Limit(1)

	sql, args := sb.BuildWithFlavor(m.flavor)

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManageEmailModel) Insert(ctx context.Context, session sqlx.Session, data *ManageEmail) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(manageEmailRowsExpectAutoSet).
		Values(data.Uuid, data.From, data.Host, data.Port, data.Username, data.Password, data.EnableSsl, data.IsVerify).BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultManageEmailModel) InsertV2(ctx context.Context, session sqlx.Session, data *ManageEmail) error {
	var statement string
	var args []any
	if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(manageEmailRowsExpectAutoSet).
			Values(data.Uuid, data.From, data.Host, data.Port, data.Username, data.Password, data.EnableSsl, data.IsVerify).Returning("id").BuildWithFlavor(m.flavor)
	} else {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(manageEmailRowsExpectAutoSet).
			Values(data.Uuid, data.From, data.Host, data.Port, data.Username, data.Password, data.EnableSsl, data.IsVerify).BuildWithFlavor(m.flavor)
	}
	var primaryKey int64
	var err error
	if session != nil {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = session.QueryRowCtx(ctx, &primaryKey, statement, args...)
			if err != nil {
				return err
			}
		} else {
			result, err := session.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	} else {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = m.conn.QueryRowCtx(ctx, &primaryKey, statement, args...)
		} else {
			result, err := m.conn.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	}
	data.Id = primaryKey
	return err
}

func (m *defaultManageEmailModel) Update(ctx context.Context, session sqlx.Session, newData *ManageEmail) error {
	sb := sqlbuilder.Update(m.table)
	split := strings.Split(manageEmailRowsExpectAutoSet, ",")
	var assigns []string
	for _, s := range split {
		if condition.Unquote(s) == condition.Unquote("`id`") {
			continue
		}
		assigns = append(assigns, sb.Assign(s, nil))
	}
	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), nil))
	statement, _ := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, newData.Uuid, newData.From, newData.Host, newData.Port, newData.Username, newData.Password, newData.EnableSsl, newData.IsVerify, newData.Id)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, newData.Uuid, newData.From, newData.Host, newData.Port, newData.Username, newData.Password, newData.EnableSsl, newData.IsVerify, newData.Id)
	}
	return err
}

func (m *defaultManageEmailModel) withTableColumns(columns ...string) []string {
	var withTableColumns []string
	for _, col := range columns {
		if strings.Contains(col, ".") {
			withTableColumns = append(withTableColumns, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableColumns = append(withTableColumns, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableColumns
}
func (m *customManageEmailModel) WithTable(f func(table string) string) manageEmailModel {
	mc := &customManageEmailModel{
		defaultManageEmailModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customManageEmailModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*ManageEmail) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.SetFlavor(m.flavor)
	sb.Cols(manageEmailRowsExpectAutoSet)
	for _, data := range datas {
		sb.Values(data.Uuid, data.From, data.Host, data.Port, data.Username, data.Password, data.EnableSsl, data.IsVerify)
	}
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customManageEmailModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conds ...condition.Condition) ([]*ManageEmail, error) {
	if len(columns) == 0 {
		columns = manageEmailFieldNames
	}
	sb := sqlbuilder.Select(m.withTableColumns(columns...)...).From(m.table)
	builder := condition.SelectWithFlavor(m.flavor, *sb, conds...)
	statement, args := builder.BuildWithFlavor(m.flavor)

	var resp []*ManageEmail
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customManageEmailModel) FindByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*ManageEmail, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, manageEmailFieldNames, conds...)
}

func (m *customManageEmailModel) CountByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (int64, error) {
	countsb := sqlbuilder.Select("count(*)").From(m.table)

	var countConds []condition.Condition
	for _, cond := range conds {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy {
			countConds = append(countConds, cond)
		}
	}
	countBuilder := condition.SelectWithFlavor(m.flavor, *countsb, countConds...)

	var (
		total int64
		err   error
	)
	statement, args := countBuilder.BuildWithFlavor(m.flavor)
	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customManageEmailModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) (*ManageEmail, error) {
	sb := sqlbuilder.Select(m.withTableColumns(manageEmailFieldNames...)...).From(m.table)

	builder := condition.SelectWithFlavor(m.flavor, *sb, conds...)
	builder.Limit(1)
	statement, args := builder.BuildWithFlavor(m.flavor)

	var resp ManageEmail
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customManageEmailModel) PageByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) ([]*ManageEmail, int64, error) {
	sb := sqlbuilder.Select(m.withTableColumns(manageEmailFieldNames...)...).From(m.table)
	builder := condition.SelectWithFlavor(m.flavor, *sb, conds...)

	var resp []*ManageEmail
	var err error

	statement, args := builder.BuildWithFlavor(m.flavor)

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conds...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customManageEmailModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conds ...condition.Condition) error {
	if field == nil {
		return nil
	}

	sb := sqlbuilder.Update(m.table)
	builder := condition.UpdateWithFlavor(m.flavor, *sb, conds...)

	var assigns []string
	for key, value := range field {
		assigns = append(assigns, sb.Assign(key, value))
	}
	builder.Set(assigns...)

	statement, args := builder.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customManageEmailModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conds ...condition.Condition) error {
	if len(conds) == 0 {
		return nil
	}
	sb := sqlbuilder.DeleteFrom(m.table)
	builder := condition.DeleteWithFlavor(m.flavor, *sb, conds...)
	statement, args := builder.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
