// Code generated by goctl. DO NOT EDIT.

package system_user_role

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero-contrib/condition"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	systemUserRoleFieldNames          = builder.RawFieldNames(&SystemUserRole{})
	systemUserRoleRows                = strings.Join(systemUserRoleFieldNames, ",")
	systemUserRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(systemUserRoleFieldNames, "`id`"), ",")
	systemUserRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(systemUserRoleFieldNames, "`id`"), "=?,") + "=?"
)

type (
	systemUserRoleModel interface {
		Insert(ctx context.Context, data *SystemUserRole) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SystemUserRole, error)
		Update(ctx context.Context, data *SystemUserRole) error
		Delete(ctx context.Context, id uint64) error

		// custom interface generated by jzero
		BulkInsert(ctx context.Context, datas []*SystemUserRole) error
		FindByCondition(ctx context.Context, conds ...condition.Condition) ([]*SystemUserRole, error)
		FindOneByCondition(ctx context.Context, conds ...condition.Condition) (*SystemUserRole, error)
		PageByCondition(ctx context.Context, conds ...condition.Condition) ([]*SystemUserRole, int64, error)
		UpdateFieldsByCondition(ctx context.Context, field map[string]any, conds ...condition.Condition) error
		DeleteByCondition(ctx context.Context, conds ...condition.Condition) error
	}

	defaultSystemUserRoleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SystemUserRole struct {
		Id         uint64        `db:"id"`
		CreateTime time.Time     `db:"create_time"`
		UpdateTime time.Time     `db:"update_time"`
		CreateBy   sql.NullInt64 `db:"create_by"`
		UpdateBy   sql.NullInt64 `db:"update_by"`
		UserId     int64         `db:"user_id"`
		RoleId     int64         `db:"role_id"`
	}
)

func newSystemUserRoleModel(conn sqlx.SqlConn) *defaultSystemUserRoleModel {
	return &defaultSystemUserRoleModel{
		conn:  conn,
		table: "`system_user_role`",
	}
}

func (m *defaultSystemUserRoleModel) Delete(ctx context.Context, id uint64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ("`id`", id))
	sql, args := sb.Build()
	_, err := m.conn.ExecCtx(ctx, sql, args...)
	return err
}

func (m *defaultSystemUserRoleModel) FindOne(ctx context.Context, id uint64) (*SystemUserRole, error) {
	sb := sqlbuilder.Select(systemUserRoleRows).From(m.table)
	sb.Where(sb.EQ("`id`", id))
	sb.Limit(1)
	sql, args := sb.Build()
	var resp SystemUserRole
	err := m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemUserRoleModel) Insert(ctx context.Context, data *SystemUserRole) (sql.Result, error) {
	sql, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(systemUserRoleRowsExpectAutoSet).
		Values(data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.UserId, data.RoleId).Build()
	ret, err := m.conn.ExecCtx(ctx, sql, args...)
	return ret, err
}

func (m *defaultSystemUserRoleModel) Update(ctx context.Context, data *SystemUserRole) error {
	sb := sqlbuilder.Update(m.table)
	split := strings.Split(systemUserRoleRowsExpectAutoSet, ",")
	var assigns []string
	for _, s := range split {
		assigns = append(assigns, sb.Assign(s, nil))
	}
	sb.Set(assigns...)
	sb.Where(sb.EQ("`id`", nil))
	sql, _ := sb.Build()
	_, err := m.conn.ExecCtx(ctx, sql, data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.UserId, data.RoleId, data.Id)
	return err
}

func (m *defaultSystemUserRoleModel) tableName() string {
	return m.table
}

func (m *customSystemUserRoleModel) BulkInsert(ctx context.Context, datas []*SystemUserRole) error {
	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(systemUserRoleRowsExpectAutoSet)
	for _, data := range datas {
		sb.Values(data.CreateTime, data.UpdateTime, data.CreateBy, data.UpdateBy, data.UserId, data.RoleId)
	}
	sql, args := sb.Build()
	_, err := m.conn.ExecCtx(ctx, sql, args...)
	return err
}

func (m *customSystemUserRoleModel) FindByCondition(ctx context.Context, conds ...condition.Condition) ([]*SystemUserRole, error) {
	sb := sqlbuilder.Select(systemUserRoleFieldNames...).From(m.table)
	condition.ApplySelect(sb, conds...)
	sql, args := sb.Build()

	var resp []*SystemUserRole
	err := m.conn.QueryRowsCtx(ctx, &resp, sql, args...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customSystemUserRoleModel) FindOneByCondition(ctx context.Context, conds ...condition.Condition) (*SystemUserRole, error) {
	sb := sqlbuilder.Select(systemUserRoleFieldNames...).From(m.table)
	condition.ApplySelect(sb, conds...)
	sb.Limit(1)
	sql, args := sb.Build()

	var resp SystemUserRole
	err := m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customSystemUserRoleModel) PageByCondition(ctx context.Context, conds ...condition.Condition) ([]*SystemUserRole, int64, error) {
	sb := sqlbuilder.Select(systemUserRoleFieldNames...).From(m.table)
	countsb := sqlbuilder.Select("count(*)").From(m.table)

	condition.ApplySelect(sb, conds...)

	var countConds []condition.Condition
	for _, cond := range conds {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset {
			countConds = append(countConds, cond)
		}
	}
	condition.ApplySelect(countsb, countConds...)

	var resp []*SystemUserRole

	sql, args := sb.Build()
	err := m.conn.QueryRowsCtx(ctx, &resp, sql, args...)
	if err != nil {
		return nil, 0, err
	}

	var total int64
	sql, args = countsb.Build()
	err = m.conn.QueryRowCtx(ctx, &total, sql, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customSystemUserRoleModel) UpdateFieldsByCondition(ctx context.Context, field map[string]any, conds ...condition.Condition) error {
	if field == nil {
		return nil
	}

	sb := sqlbuilder.Update(m.table)
	condition.ApplyUpdate(sb, conds...)

	var assigns []string
	for key, value := range field {
		assigns = append(assigns, sb.Assign(key, value))
	}
	sb.Set(assigns...)

	sql, args := sb.Build()
	_, err := m.conn.ExecCtx(ctx, sql, args...)
	if err != nil {
		return err
	}
	return nil
}

func (m *customSystemUserRoleModel) DeleteByCondition(ctx context.Context, conds ...condition.Condition) error {
	if len(conds) == 0 {
		return nil
	}
	sb := sqlbuilder.DeleteFrom(m.table)
	condition.ApplyDelete(sb, conds...)
	sql, args := sb.Build()
	_, err := m.conn.ExecCtx(ctx, sql, args...)
	return err
}
