// Code generated by jzero. DO NOT EDIT.
package system_managemenu

import (
	"time"
)

var (
	_ = time.Now()
)

type GetAllPagesRequest struct {
}

type GetAllPagesResponse struct {
}

type ListRequest struct {
}

type ListResponse struct {
}

type TreeRequest struct {
}

type TreeResponse struct {
}
