name: web

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web.yaml'

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: web/pnpm-lock.yaml

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: Build web
        run: |-
          cd web
          pnpm i
          VITE_SERVICE_BASE_URL=https://demo.jzero-admin-api.jaronnie.com pnpm build
          VITE_SERVICE_BASE_URL=http://jzero-admin-server.fcv3.1446568277794229.cn-hangzhou.fc.devsapp.net pnpm build --outDir fc3-dist
          cd ..

      - name: Upload to jaronnie/jzero-admin-deploy-web
        run: |
          go install github.com/jaronnie/grum@latest
          GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }} grum clone https://github.com/jaronnie/jzero-admin-deploy-web
          cd jzero-admin-deploy-web
          git config user.name "dependabot[bot]"
          git config user.email "49699333+dependabot[bot]@users.noreply.github.com"
          find . -type f -mindepth 1 ! -path "./vercel.json" ! -path "./.git/*" ! -path "./code/nginx.conf" ! -path "./s.yaml" -exec rm -rf {} +
          mv ../web/dist/* ./
          mv ../web/fc3-dist/* ./code/build
          git add .
          git diff-index --quiet HEAD || git commit -m "feat(web): update"
          git push -f
